src/routes/feedback.py
from flask import Blueprint, request, flash, url_for, redirect, render_template
from flask_login import login_required, current_user

from extensions.db import db
from models.FeedbackEntry import FeedbackEntry
from models.User import User
from routes.util import FLASH_DANGER, FLASH_SUCCESS

feedback_bp = Blueprint('feedback', __name__)


@feedback_bp.route('/feedback-received')
@login_required
def received():
    feedback = current_user.received_feedback
    return render_template("received_feedback.html", feedback=feedback)


@feedback_bp.route('/feedback-given')
@login_required
def given():
    feedback = current_user.given_feedback
    return render_template("given_feedback.html", feedback=feedback)


@feedback_bp.route('/feedback/delete')
def delete():
    id_to_delete = request.args.get('id')
    maybe_feedback = FeedbackEntry.query.get(id_to_delete)
    if not maybe_feedback or maybe_feedback.giver != current_user:
        flash("Kann nicht gelöscht werden", FLASH_DANGER)
        return redirect(url_for('feedback.given'))
    db.session.delete(maybe_feedback)
    db.session.commit()
    flash("Erfolgreich gelöscht", FLASH_SUCCESS)
    return redirect(url_for('feedback.given'))


@feedback_bp.route('/send-feedback')
@login_required
def send():
    receiver_id = request.args.get('receiver')
    maybe_receiver = User.query.get(receiver_id)
    if not maybe_receiver:
        flash("Diesen User kennen wir nicht", FLASH_DANGER)
        return redirect(url_for('room.overview'))

    if current_user.room != maybe_receiver.room:
        flash("Don't break it, dieser User gehört nicht zu deinem Room!", FLASH_DANGER)
        return redirect(url_for('room.overview'))

    return render_template("send_feedback.html", receiver=maybe_receiver)


@feedback_bp.route('/edit-feedback')
@login_required
def edit():
    feedback_id = request.args.get('id')
    maybe_feedback = FeedbackEntry.query.get(feedback_id)
    if not maybe_feedback or maybe_feedback.giver != current_user:
        flash("Ah fuck off", FLASH_DANGER)
        return redirect(url_for('feedback.given'))

    return render_template("send_feedback.html", receiver=maybe_feedback.receiver, content=maybe_feedback)


@feedback_bp.route('/save-feedback', methods=['POST'])
@login_required
def save():
    id_to_update = request.form.get('id_to_update')

    receiver = request.form.get('receiver_id')
    text = request.form.get('feedback_message')
    anonymous = True if request.form.get('send_anonymously') else False

    if id_to_update:
        maybe_feedback = FeedbackEntry.query.get(id_to_update)
        if not maybe_feedback or maybe_feedback.giver != current_user:
            flash("Ah fuck off", FLASH_DANGER)
            return redirect(url_for('feedback.given'))
        maybe_feedback.text = text
        maybe_feedback.anonymous = anonymous
        db.session.commit()
        flash("Erfolgreich aktualisiert", FLASH_SUCCESS)
        return redirect(url_for('feedback.given'))

    maybe_receiver = User.query.get(receiver)
    if not maybe_receiver:
        flash("Diesen Benutzer kennen wir nicht.", FLASH_DANGER)
        return redirect(url_for('room.overview'))

    if not text:
        flash("Musst schon was eingeben du Depp", FLASH_DANGER)
        return redirect(url_for('room.overview'))

    entry = FeedbackEntry(current_user, maybe_receiver, text, anonymous)
    db.session.add(entry)
    db.session.commit()

    flash("Feedback gespeichert, danke!", FLASH_SUCCESS)
    return redirect(url_for('room.overview'))

src/routes/login.py
from flask import Blueprint, render_template, request, flash, url_for as for1
from werkzeug.utils import redirect as redirect1

from extensions.db import db
from flask_login import login_user, login_required, logout_user

from models.Room import Room
from models.User import User
from routes.util import *

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
def index():
    return render_template('login.html')

@login_bp.route('/sign-up')
def index_sign_up():
    invite_id = request.args.get("invite_id")

    maybe_room = None
    if invite_id:
        maybe_room = Room.query.get(invite_id)
        if not maybe_room:
            flash("Sorry, dieser Link ist ungültig. Frage deinen Host nach dem richtigen Link.",
                  FLASH_DANGER)

    return render_template('sign_up.html', room=maybe_room)


@login_bp.route('/login', methods=['POST'])
def login():
    email = request.form.get('user_id')
    password = request.form.get('password')

    maybe_user: User = User.query.filter_by(email=email).first()
    if maybe_user.check_login(password):
        login_user(maybe_user)
        return redirect(url_for("room.overview"))
    else:
        flash(f"Das Passwort ist falsch", FLASH_DANGER)
        return redirect(url_for('.index'))


@login_bp.route('/sign-up', methods=['POST'])
def sign_up():
    room_id = request.form.get('room_id')
    email = request.form.get('user_id')
    password = request.form.get('password')

    if not room_id or not email or not password:
        flash(f"Unvollständig", FLASH_DANGER)
        return redirect(url_for('.index', invite_id=room_id))

    maybe_room = Room.query.get(room_id)
    if not maybe_room:
        flash(f"Raum {room_id} konnte nicht gefunden werden", FLASH_DANGER)
        return redirect1(for1('.index'))

    maybe_user: User = User.query.filter_by(email=email).first()
    if maybe_user:
        flash("Es gibt schon einen Account mit dieser Email Adresse", FLASH_DANGER)
        return redirect(url_for('login.index', invite_id=room_id))

    new_user = User(email, password, maybe_room)
    db.session.add(new_user)
    db.session.commit()
    flash("Erfolgreich registiert!", FLASH_SUCCESS)
    login_user(new_user)
    return redirect(url_for("profile.view"))


@login_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect_login()


def redirect_login():
    return redirect(url_for('login.index'))


@login_bp.route('/about')
def about():
    return render_template('about.html')

src/routes/profile.py
from flask import Blueprint, render_template, request, send_file, flash
from extensions.db import db
from extensions.image_service import image_service
from flask_login import login_required, current_user

from models.Room import Room
from models.User import User
from routes.util import *

profile_bp = Blueprint('profile', __name__)

@profile_bp.route('/profile')
@login_required
def view():
    user: User = current_user
    return render_template("profile_settings.html", user=user)


@profile_bp.route('/profile/edit', methods=['POST'])
@login_required
def edit():
    user: User = current_user
    user.firstname = request.form.get("firstname")
    user.lastname = request.form.get("lastname")
    user.info = request.form.get("info")
    db.session.commit()
    return redirect(url_for(".view"))


@profile_bp.route('/profile/upload_pic', methods=['POST'])
@login_required
def upload_pic():
    pic = request.files['pic']
    if pic.filename != '':
        old_filename = current_user.profile_pic
        new_filename = image_service.crop_and_save_pic(pic)
        current_user.profile_pic = new_filename
        db.session.commit()
        image_service.delete_file(old_filename)
    return redirect(url_for(".view"))


@profile_bp.route('/profile/<user_id>/delete', methods=['GET'])
@login_required
def delete_user(user_id):
    maybe_user = User.query.get(user_id)
    admin_key = request.args.get('admin_key')
    maybe_room = Room.query.filter_by(admin_key=admin_key).first()
    if not maybe_user or not maybe_room or not maybe_user.room == maybe_room:
        flash("Nope, you not do this", FLASH_DANGER)
        return redirect(url_for('login.index'))
    db.session.delete(maybe_user)
    db.session.commit()
    image_service.delete_file(maybe_user.profile_pic)
    flash("User erfolgreich gelöscht", FLASH_SUCCESS)
    return redirect(url_for('room.edit_form', admin_key=admin_key))


@profile_bp.route('/profile/<user_id>/set-password', methods=['POST'])
@login_required
def admin_change_password(user_id):
    maybe_user = User.query.get(user_id)
    admin_key = request.args.get('admin_key')
    maybe_room = Room.query.filter_by(admin_key=admin_key).first()
    if not maybe_user or not maybe_room or not maybe_user.room == maybe_room:
        flash("Nope, you not do this", FLASH_DANGER)
        return redirect(url_for('login.index'))
    new_password = request.form.get('password')
    maybe_user.change_password(new_password)
    db.session.commit()
    flash(f"Passwort für {maybe_user.firstname} geändert", FLASH_SUCCESS)
    return redirect(url_for('room.edit_form', admin_key=admin_key))

src/routes/room.py
from flask import Blueprint, render_template, request, current_app, flash, send_file
from flask_login import login_required, current_user

from extensions.db import db
from extensions.limiter import limiter
from extensions.image_service import image_service
from models.Room import Room
from models.User import User
from routes.util import *

room_bp = Blueprint('room', __name__)


@room_bp.route("/overview")
@login_required
def overview():
    user: User = current_user
    room_users = [u for u in user.room.users]
    room_users.remove(user)
    return render_template("overview.html", room_users=room_users)


@room_bp.route('/create-room')
def create_room():
    return render_template("create_room.html")


@room_bp.route('/edit-room')
def edit_form():
    admin_key = request.args.get('admin_key')
    maybe_room = Room.query.filter_by(admin_key=admin_key).first()
    if not maybe_room:
        flash("Dieser Key ist falsch", FLASH_DANGER)
        return redirect(url_for('login.index'))
    return render_template("edit_room.html", room=maybe_room)


@limiter.limit("1 per minute")
@room_bp.route('/create-room', methods=['POST'])
def create():
    room_name = request.form.get('room_name')
    maybe_room_pic = request.files.get('room_picture')
    pri_color = request.form.get('primary_color')
    sec_color = request.form.get('secondary_color')

    room_pic = None
    if maybe_room_pic:
        room_pic = image_service.crop_and_save_pic(maybe_room_pic)

    room = Room(room_name, room_pic, pri_color, sec_color)
    db.session.add(room)
    db.session.commit()
    return render_template('room_created.html', room=room)


@limiter.limit("1 per second")
@room_bp.route('/edit-room', methods=['POST'])
def edit():
    room_name = request.form.get('room_name')
    maybe_room_pic = request.files.get('room_picture')
    pri_color = request.form.get('primary_color')
    sec_color = request.form.get('secondary_color')
    admin_key = request.form.get('key_to_update')

    maybe_room = Room.query.filter_by(admin_key=admin_key).first()
    if not maybe_room:
        flash("Dieser Key ist falsch", FLASH_DANGER)
        return redirect(url_for('login.index'))


    if maybe_room_pic:
        room_pic = image_service.crop_and_save_pic(maybe_room_pic)
        old_filename = maybe_room.room_pic
        maybe_room.room_pic = room_pic
        if old_filename:
            image_service.delete_file(old_filename)
    maybe_room.name = room_name
    maybe_room.primary_color = pri_color
    maybe_room.secondary_color = sec_color
    db.session.commit()

    flash("Raum erfolgreich aktualisiert", FLASH_SUCCESS)
    return redirect(url_for('.edit_form', admin_key=admin_key))

src/templates/edit_room.html
{% extends "base.html" %}

{% block title %}Raum bearbeiten{% endblock %}


{% block content %}
    <div class="container">
        <div class="row mb-5"></div>
        <div class="row">
            <div class="col"></div>
            <div class="col-lg-8 col-sm-12">
                <div class="card bg-light">
                    <div class="card-body">
                        <div class="row justify-content-md-center">
                            <div class="col-lg-12 col-sm-12 text-center">
                                <h5 class="card-title">Passe deinen Raum an</h5>
                            </div>
                        </div>
                        <div class="row justify-content-md-center">
                            <div class="col-lg-12 col-sm-12 text-center">
                                <img src="../static/img/logo.png" class="logo">
                            </div>
                        </div>
                        <form method="POST" action="{{ url_for('room.edit') }}" enctype="multipart/form-data">
                            <div class="row justify-content-md-center">
                                <div class="form-group col-lg-6 col-sm-12">
                                    <label for="room_name">Name des Raums</label>
                                    <input type="text" class="form-control" name="room_name"
                                           value="{{ room.name }}"
                                           placeholder="Dualer Summit Feedback Room">
                                </div>
                            </div>
                            <div class="row justify-content-md-center mt-2 mb-3">
                                <div class="col-lg-6 col-sm-12 text-center">
                                    <label class="form-label" for="profil_pic">Lade ein Logo für deinen Raum hoch</label>
                                    <input type="file" name="room_picture" class="form-control bg-light" id="pic" accept="image/jpeg, image/png" />
                                </div>
                            </div>
                            <div class="row justify-content-md-center">
                                <div class="form-group col-lg-6 col-sm-12">
                                    <label for="primary_color">Primäre Farbe</label>
                                    <input type="color" class="form-control" name="primary_color"
                                           value="{{ room.primary_color }}">
                                </div>
                            </div>
                            <div class="row justify-content-md-center">
                                <div class="form-group col-lg-6 col-sm-12">
                                    <label for="secondary_color">Sekundäre Farbe</label>
                                    <input type="color" class="form-control" name="secondary_color"
                                           value="{{ room.secondary_color }}">
                                </div>
                            </div>
                            <div class="row justify-content-center">

                                <div class="col-lg-3 col-sm-12 text-center">
                                        <input type="text" name="key_to_update" value="{{ room.admin_key }}"
                                               hidden>
                                    <button type="submit" class="btn btn-primary w-100">Änderungen speichern</button>
                                </div>
                            </div>
                        </form>
                        <div class="row mb-5"></div>

                        
                    </div>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-8">

            {% for user in room.users %}
            <div class="row mt-3 pt-3 pb-3 justify-content-start bg-light border rounded align-items-center">
                <div class="col d-none d-lg-block d-xl-block">
                    <img src="{{ get_profile_pic(user) }}" class="profil-image small-image">
                </div>
                <div class="col-lg-5">
                    <div class="row">
                        <div class="col-lg-12 col-sm-12">
                            <h5>{{ user.firstname }} {{ user.lastname }}</h5>
                        </div>
                    </div>
                </div>
                <form method="POST" action="{{ url_for('profile.admin_change_password', user_id=user.id, admin_key=room.admin_key) }}">
                    <div id="user_id_{{ user.id }}" class="col" id="new_password_section">
                        <input class="btn btn-primary w-100 btn-change-password user_id_{{ user.id }}" type="submit" value="Passwort ändern">
                    </div>
                </form>
                <div class="col">
                    <a href="{{ url_for('profile.delete_user', user_id=user.id, admin_key=room.admin_key) }}" class="btn btn-danger w-100">User löschen</a>
                </div>
            </div>
            {% endfor %}

        </div>

    </div>

{% endblock %}

{% block script %}
<script>

$(".btn-change-password").on('click', function(event){
    var random_password = Math.random().toString(36).slice(-8);
    user_id = $(this).attr('class').split(' ').pop();
    html=`<div id="user_id_${user_id}" class="col" id="new_password_section">
           <input type="text" id="password" name="password" value="${random_password}">
           <input class="btn btn-primary w-100 btn-change-password user_id_${user_id}" type="submit" value="Passwort speichern">
        </div>
        `;

    $( "#" + user_id ).replaceWith(html);
    console.log(user_id);
});

</script>
{% endblock %}

src/templates/index.html
{% extends "base.html" %}

{% block title %}BI X-mas challenge{% endblock %}

{% block header %}
    <p></p>
    <div class="jumbotron">
        <p>Some Headline</p>
    </div>
{% endblock %}

{% block content %}
    <h2>Something</h2>
    {% if room %} Your room is: {{ room.name }} {% endif %}
    <p>HTML goes here</p>

    <script>
        // Javascript if needed here
    </script>
{% endblock %}

src/templates/login.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <link href="../static/styles.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none"/>
    <title>Feedio</title>
</head>

<body>

<div class="container">
    <div class="row mb-5"></div>
    <div class="row">
        <div class="col"></div>
        <div class="col-lg-8 col-sm-12">
            <div class="card bg-light">
                <div class="card-body">
                    <div class="row justify-content-md-center">
                        <div class="col-lg-12 col-sm-12 text-center">
                            {% if room %}
                                <h5 class="card-title">Willkommen im Raum {{ room.name }} </h5>
                            {% else %}
                                <h5 class="card-title">Willkommen auf Feedi</h5>
                            {% endif %}
                            <h5 class="card-title"></h5>
                        </div>
                    </div>
                    <div class="row justify-content-md-center">
                        <div class="col-lg-12 col-sm-12 text-center">
                            <img src="../static/img/logo.png" class="logo">
                        </div>
                    </div>
                    {% with messages = get_flashed_messages(True) %}
                        {% if messages %}
                            <div class="row">
                                <div class="col">
                                    {% for m in messages %}
                                        <div class="alert alert-{{ m[0] }} alert-dismissible fade show">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            {{ m[1] }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endif %}
                    {% endwith %}
                    <form method="POST" action="{{ url_for('login.login') }}">
                        <div class="row justify-content-md-center">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="room_id">ID des Raums</label>
                                <input type="text" class="form-control" name="room_id" required
                                       placeholder="Dualer Summit Feedback Room" {% if room %}readonly
                                       value="{{ room.id }}" {% endif %}>
                            </div>
                        </div>
                        <div class="row justify-content-md-center">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="user_id">User ID</label>
                                <input type="email" class="form-control" name="user_id"
                                       placeholder="max.mustermann@web.de">
                            </div>
                        </div>
                        <div class="row justify-content-md-center">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="password">Passwort</label>
                                <input type="password" class="form-control" name="password"
                                       placeholder="Dein Passwort">
                            </div>
                        </div>

                        <div class="row justify-content-center">

                            <div class="col-lg-3 col-sm-3 text-center">
                                <button class="btn btn-outline-primary w-100" name="type" value="sign_up"
                                        type="submit">
                                    Registrieren
                                </button>
                            </div>
                            <div class="col-lg-3 col-sm-3 text-center">
                                <button class="btn btn-primary w-100" name="type" value="login" type="submit">
                                    Anmelden
                                </button>
                            </div>
                        </div>
                    </form>
                    <div class="row mt-5 justify-content-center">
                        <div class="col text-center"><a href="{{ url_for('room.create') }}">Erstelle hier einen neuen Raum!</a></div>
                    </div>
                    <div class="row mt-5 justify-content-center">
                        <div class="col text-center"><a href="{{ url_for('login.about') }}">Wie funktioniert's?</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
    {% if messages %}
        <div class="row">
            <div class="col">
                {% for m in messages %}
                    <div class="alert alert-{{ m[0] }} alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ m[1] }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>

<script>

</script>
</body>

</html>

src/templates/sign_up.html
<!DOCTYPE html>
<html lang="de">

<head>
    <meta charset="UTF-8">
    <link href="../static/styles.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none"/>
    <title>Feedio - Registrieren</title>
</head>

<body>

<div class="container">
    <div class="row mb-5"></div>
    <div class="row">
        <div class="col"></div>
        <div class="col-lg-8 col-sm-12">
            <div class="card bg-light">
                <div class="card-body">
                    <div class="row justify-content-md-center">
                        <div class="col-lg-12 col-sm-12 text-center">
                            {% if room %}
                                <h5 class="card-title">Willkommen im Raum {{ room.name }} </h5>
                            {% else %}
                                <h5 class="card-title">Willkommen auf Feedi</h5>
                            {% endif %}
                            <h5 class="card-title"></h5>
                        </div>
                    </div>
                    <div class="row justify-content-md-center">
                        <div class="col-lg-12 col-sm-12 text-center">
                            <img src="../static/img/logo.png" class="logo">
                        </div>
                    </div>
                    {% with messages = get_flashed_messages(True) %}
                        {% if messages %}
                            <div class="row">
                                <div class="col">
                                    {% for m in messages %}
                                        <div class="alert alert-{{ m[0] }} alert-dismissible fade show">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            {{ m[1] }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endif %}
                    {% endwith %}
                    <form method="POST" action="{{ url_for('login.sign_up') }}">
                        <div class="row justify-content-md-center">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="room_id">ID des Raums</label>
                                <input type="text" class="form-control" name="room_id" required placeholder="Frage den Admin des Raums"
                                       value="{{ room.id }}">
                            </div>
                        </div>
                        <div class="row justify-content-md-center">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="user_id">User ID</label>
                                <input required type="email" class="form-control" name="user_id"
                                       placeholder="max.mustermann@web.de">
                            </div>
                        </div>
                        <div class="row justify-content-md-center">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="password">Passwort</label>
                                <input required type="password" class="form-control" name="password" id="password"
                                       placeholder="Dein Passwort">
                            </div>
                        </div>
                        <div class="row justify-content-md-center">
                            <div class="form-group col-lg-6 col-sm-12">
                                <label for="password">Passwort wiederholen</label>
                                <input required type="password" class="form-control" name="password" id="password-2"
                                       placeholder="Dein Passwort">
                            </div>
                        </div>

                        <div hidden class="row justify-content-md-center" id="validation-messages">
                            <div class="form-group col-lg-6 col-sm-12 text-center text-danger" id="message">
                            </div>
                        </div>

                        <div class="row justify-content-center">

                            <div class="col-lg-3 col-sm-3 text-center">
                                <button class="btn btn-primary w-100" name="type" value="sign_up"
                                        type="submit">
                                    Registrieren
                                </button>
                            </div>
                        </div>
                    </form>
                    <div class="row mt-1 mb-5 justify-content-center">
                        <div class="col text-center"><a href="{{ url_for('login.index') }}">Du hast bereits einen Account?</a></div>
                    </div>
                    <div class="row mt-5 justify-content-center">
                        <div class="col text-center"><a href="{{ url_for('room.create') }}">Erstelle hier einen neuen Raum!</a></div>
                    </div>
                    <div class="row mt-5 justify-content-center">
                        <div class="col text-center"><a href="{{ url_for('login.about') }}">Wie funktioniert's?</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
    {% if messages %}
        <div class="row">
            <div class="col">
                {% for m in messages %}
                    <div class="alert alert-{{ m[0] }} alert-dismissible fade show">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ m[1] }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>



{% block script %}
<script>
    $( "form" ).submit(function( event ) {
      if ( $( "#password" ).val() === $( "#password-2" ).val() ) {
        return;
      } else {
        $( "#validation-messages" ).attr("hidden",false);
        $( "#message" ).html("Die Passwörter sind nicht identisch.");
        return false;
      }
    });
    </script>
{% endblock %}


</body>

</html>